---
  - hosts: all
    become: yes
    gather_facts: yes

    tasks:
      - name: make sure snapd is installed
        apt:
          name: snapd
          state: latest
          update_cache: yes

      - name: install microk8s snap
        become: yes
        shell: snap install microk8s --classic

      - name: get kubernetes deployment yaml file
        get_url:
          url: https://raw.githubusercontent.com/kanuahs/flask-sample-app/master/kubernetes-deployment.yaml
          dest: ~/kubernetes-deployment.yaml

      - name: get kubernetes service yaml file
        get_url:
            url: https://raw.githubusercontent.com/kanuahs/flask-sample-app/master/kubernetes-service.yaml
            dest: ~/kubernetes-service.yaml

      - name: make sure that microk8s is ready before trying to deploy anything
        shell: microk8s.status --wait-ready

      - name: create a sample deployment
        shell: microk8s.kubectl apply -f ~/kubernetes-deployment.yaml

      - name: create a sample service
        shell: microk8s.kubectl apply -f ~/kubernetes-service.yaml